services:

  mariadb:
    image: mariadb
    env_file: .env
    restart: always
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception_network
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    env_file: .env
    restart: always
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - redis
      - mariadb
    networks:
      - inception_network
    volumes:
      - wp_data:/var/www/wordpress

  nginx:
    image: nginx
    env_file: .env
    restart: always
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wp_data:/var/www/wordpress

  ftp:
    image: ftp
    env_file: .env
    restart: always
    container_name: ftp
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    networks:
      - inception_network
    volumes:
      - wp_data:/var/www/wordpress
    
  redis:
    image: redis
    env_file: .env
    restart: always
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - inception_network
    volumes:
      - redis_data:/data

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  wp_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/vboxuser/data/wordpress' #vm_path
      # device: '/home/alassiqu/data/wordpress' #1337_path
      # device: '/home/itsmeachraf/data/wordpress' #home_path
  db_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/vboxuser/data/mariadb' #vm_path
      # device: '/home/alassiqu/data/mariadb' #1337_path
      # device: '/home/itsmeachraf/data/mariadb' #home_path
  redis_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/vboxuser/data/redis' #vm_path
      # device: '/home/alassiqu/data/redis' #1337_path
      # device: '/home/itsmeachraf/data/redis' #home_path
