FROM	debian:bullseye

RUN		apt update -y && apt install mariadb-server -y

COPY	conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf 

COPY	tools/init_mariadb.sh	/

RUN 	chmod 755 init_mariadb.sh


CMD 	["bash", "init_mariadb.sh"]
