FROM        debian:bullseye

RUN         apt update && \
            apt install -y php php-mysqli wget unzip

RUN         mkdir -p /var/www/html && \
            wget "https://github.com/vrana/adminer/releases/download/v5.3.0/adminer-5.3.0.php" -O /var/www/html/index.php

EXPOSE      8080

CMD         ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
